spring:
  application:
    name: pallow
  jpa:
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DB_URL}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: 'true'
          timeout: 5000
          starttls:
            enable: 'true'
            required: 'true'
data:
  redis:
    host: localhost
    port: 6379

  web:
    resources:
      add-mappings: true
  mvc:
    static-path-pattern: /static/**
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  access-token:
    ttl: ${ACCESS_TOKEN_TTL}
  refresh-token:
    ttl: ${REFRESH_TOKEN_TTL}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
kakao:
  clientId: ${CLIENT_ID}
  redirectUri: ${REDIRECT_URI}
