spring:
  application:
    name: pallow
  jpa:
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DB_URL}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: 'true'
          timeout: 5000
          starttls:
            enable: 'true'
            required: 'true'

      redis:
        host: localhost
        port: 6379

  web:
    resources:
      add-mappings: true

jwt:
  secret:
    key: ${JWT_KEY}
  access:
    expiration: ${JWT_ACCESS_EXPIRED_TIME}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRED_TIME}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

custom:
  headers:
    access: "Authorization"
    refresh: "X-Refresh-Token"
    authorization: "auth"
    bearer: "Bearer "

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html