### 회원가입
POST http://localhost:8080/auth/local/signup
Content-Type: application/json

{
  "username": "testuser55",
  "password": "password55",
  "nickname": "testuser55",
  "email": "test@gmail.com"
}

### 로그인
POST http://localhost:8080/auth/local
Content-Type: application/json

{
  "username": "testuser1",
  "password": "password1"
}

> {%
  client.log(response.headers.valueOf("Authorization"));
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
%}
