### 회원가입
POST http://localhost:8080/auth/local/signup
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "nickname": "{{nickname}}",
  "email": "{{email}}",
  "name" : "{{name}}",
  "gender": "MAN"
}

### 로그인
POST http://localhost:8080/auth/local
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
  client.log(response.headers.valueOf("Authorization"));
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
%}

### 채팅방 생성
POST http://localhost:8080/api/chat/rooms
Content-Type: application/json
Authorization: {{Authorization}}

{
  "name": "Test Chat Room"
}

### 채팅방 입장
GET http://localhost:8080/api/chat/rooms/1
Authorization: {{Authorization}}

### 메시지 전송
POST http://localhost:8080/api/chat/messages
Content-Type: application/json
Authorization: {{Authorization}}

{
  "chatRoomId": 1,
  "content": "Hello, this is a test message!",
  "type": "CHAT"
}

### 채팅방 목록 조회
GET http://localhost:8080/api/chat/rooms
Authorization: {{Authorization}}