### 리뷰생성
POST http://localhost:8080/meets/1/review
Authorization: {{Authorization}}
Content-Type: application/json

{
  "content": "content",
  "starRating": 5
}

### 리뷰선택조회
GET http://localhost:8080/meets/1/review/1
Authorization: {{Authorization}}
Content-Type: application/json

### 리뷰전체조회
GET http://localhost:8080/meets/1/review
Authorization: {{Authorization}}
Content-Type: application/json

### 리뷰수정
PATCH http://localhost:8080/meets/1/review/1
Authorization: {{Authorization}}
Content-Type: application/json

{
  "content": "updated content"
}

### 리뷰삭제
DELETE http://localhost:8080/meets/2/review/1
Authorization: {{Authorization}}
Content-Type: application/json

### 리뷰 좋아요
POST http://localhost:8080/review/2/like
Authorization: {{Authorization}}
Content-Type: application/json




