### 그룹생성
POST http://localhost:8080/meets/1
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VybmFtZTIiLCJhdXRoIjoiVVNFUiIsImlhdCI6MTcyMTgwOTk0NSwiZXhwIjoxNzIxODE2MzQ1fQ.MxwmYPjYt18snO0ixIFulq05uwBxBc9yCLbyNeU0JRYJlkBvcBvwMTt5-5rBMRgNRZGoW7n-I3RA0KlmJKXiIQ
Authorization: {{Authorization}}
Content-Type: application/json

{
  "title": "title 1",
  "content": "content 1"
}

### 그룹 선택 조회
GET http://localhost:8080/meets/1
Authorization: {{Authorization}}
Content-Type: application/json

### 그룹 전체 조회
GET http://localhost:8080/meets
Authorization: {{Authorization}}
Content-Type: application/json

### 그룹 수정
PATCH http://localhost:8080/meets/1
Authorization: {{Authorization}}
Content-Type: application/json

{
  "title": "updated title",
  "content": "updated content"
}

### 그룹 삭제
DELETE http://localhost:8080/meets/1
Authorization: {{Authorization}}
Content-Type: application/json


