### 회원 프로필 생성
POST http://localhost:8080/profiles/1
Authorization: {{Authorization}}
Content-Type: application/json

{
  "content": "난 멋쟁이입니다.",
  "birth": "2001-12-20",
  "gender": "MAN",
  "mbti": "ISFJ",
  "hobby": "런닝"
}

### 회원 프로필 수정
PATCH http://localhost:8080/profiles/1
Authorization: {{Authorization}}
Content-Type: application/json

{
  "content": "난 못난이입니다.",
  "birth": "2111-11-11",
  "gender": "WOMAN",
  "mbti": "ESFJ",
  "hobby": "달리기"
}

### 회원 프로필 삭제 ( 회원탈퇴 시 )
DELETE http://localhost:8080/profiles/1
Authorization: {{Authorization}}