### 회원 프로필 생성
POST http://localhost:8080/profiles/2
Authorization: {{Authorization}}
Cookie: {{Cookie}}
Content-Type: application/json


{
  "content": "난 멋쟁이입니다.",
  "birth": "2001-12-20",
  "gender": "MAN",
  "mbti": "ISFJ",
  "position": "서울특별시",
  "districtCode": 11010,
  "photo": "https://cdn2.ppomppu.co.kr/zboard/data3/2022/0509/20220509173224_d9N4ZGtBVR.jpeg"
}

### 회원 프로필 수정
PATCH http://localhost:8080/profiles/1
Authorization: {{Authorization}}
Content-Type: application/json

{
  "content": "난 못난이입니다.",
  "birth": "2111-11-11",
  "gender": "WOMAN",
  "mbti": "ESFJ",
  "position": "강원도",
  "districtCode": 32360,
  "photo": "https://img1.daumcdn.net/thumb/R1280x0/?fname=http://t1.daumcdn.net/brunch/service/user/7r5X/image/9djEiPBPMLu_IvCYyvRPwmZkM1g.jpg"
}

### 프로필 조회
GET http://localhost:8080/profiles/101
Authorization: {{Authorization}}

### 회원 프로필 삭제 ( 회원탈퇴 시 )
DELETE http://localhost:8080/profiles/1
Authorization: {{Authorization}}

### 회원 추천 받기
GET http://localhost:8080/profiles/recommendations
Authorization: {{Authorization}}
Content-Type: application/json