### 유저 게시글 생성
POST http://localhost:8080/users/1/userboards
Authorization: {{Authorization}}
Cookie: {{Cookie}}
Content-Type: application/json

{
  "title": "OOTD",
  "content": "청바지, 흰티, 파랑모자",
  "photo": "대충 사진"
}

### 유저 게시글 수정
PATCH http://localhost:8080/users/1/userboards/4
Authorization: {{Authorization}}
Content-Type: application/json

{
  "title": "제목 수정",
  "content": "내용 수정",
  "photo": "사진 수정"
}

### 유저 게시글 삭제
DELETE http://localhost:8080/users/1/userboards/1
Authorization: {{Authorization}}

### 유저 게시글 단건 조회
GET http://localhost:8080/users/1/userboards/2
Authorization: {{Authorization}}
Content-Type: application/json

### 유저 게시글 모두 조회
GET http://localhost:8080/users/1/userboards
Authorization: {{Authorization}}
Content-Type: application/json