### 유저 회원 가입
POST http://localhost:8080/auth/local/signup
Content-Type: application/json

{
  "username":"{{username}}",
  "nickname":"{{nickname}}",
  "password":"{{password}}",
  "email":"{{email}}"
}

### 로그인
POST http://localhost:8080/auth/local
Content-Type: application/json

{
  "username":"{{username}}",
  "password":"{{password}}"
}

> {%
  client.log(response.headers.valueOf("Authorization"));
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
%}