package com.pallow.pallow.domain.profile.enums;

public enum Interest {
    MOVIE("영화"),
    NETFLIX("넷플"),
    DRAMA("드라마"),
    TV_SHOW("TV예능"),
    WEBTOON("웹툰"),
    HIKING("등산"),
    GAMING("게임"),
    GOLF("골프"),
    DANCE("춤"),
    WALKING("산책"),
    PILATES_YOGA("필라테스/요가"),
    CYCLING("자전거"),
    BOWLING("볼링"),
    BILLIARDS("당구"),
    DRAWING("그림그리기"),
    PHOTOGRAPHY("사진찍기"),
    LISTENING_MUSIC("음악듣기"),
    PLAYING_INSTRUMENT("악기연주"),
    CONCERT("콘서트"),
    TATTOO("타투"),
    COSPLAY("코스프레"),
    BOARD_GAME("보드게임"),
    BAR("바"),
    FINE_DINING("파인다이닝"),
    INSTAGRAM("인스타그램"),
    CAFE("카페"),
    OMAKASE("오마카세"),
    WINE("와인"),
    COIN_KARAOKE("코인노래방"),
    CHAT("수다"),
    SHOPPING("쇼핑"),
    BEER("맥주"),
    READING("독서"),
    FOOD_TRAVEL("맛집 탐방"),
    TRAVEL("여행"),
    SPORTS_SPECTATOR("스포츠 관람"),
    CAMPING("캠핑"),
    DOING_NOTHING("멍 때리기"),
    COOKING("요리"),
    BAKING("베이킹"),
    PETS_PLANTS("반려 동/식물"),
    COMIC_CAFE("만화카페"),
    ESCAPE_ROOM("방탈출"),
    EXHIBITION("전시회 관람"),
    DRIVE("드라이브"),
    SELF_IMPROVEMENT("자기개발"),
    STUDY_CAFE("카공"),
    CERTIFICATION("자격증따기"),
    FOREIGN_LANGUAGE("외국어 공부"),
    ONE_DAY_CLASS("원데이 클래스"),
    VOLUNTEER("봉사활동"),
    FINANCIAL_PLANNING("재테크"),
    FITNESS("헬스"),
    CLIMBING("클라이밍"),
    TENNIS("테니스"),
    BADMINTON("배드민턴");

    private String description;

    Interest(String koreanName) {
        this.description = koreanName;
    }
}
