on:
  push:
    branches:
      - main
      - front-2-test

env:
  DOCKER_IMAGE_TAG_NAME: pal-world

jobs:
  build-and-docker-push:
    runs-on: ubuntu-20.04 # 실행환경

    # 실행 스텝 지정
    steps:
      - uses: actions/checkout@v3

      # java version 지정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build
      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_TAG_NAME }}:latest



  deploy-to-ec2:
    needs: build-and-docker-push # 위의 build-and-docker-push 이 끝나고 실행
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}     // 공개 도메인
          username: ${{ secrets.EC2_USER }} // ubuntu
          key: ${{ secrets.EC2_KEY }}       // SSH pem 키 값
          script: |
            CONTAINER_ID=$(sudo docker ps -q --filter "publish=8080-8080")
            
            if [ ! -z "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi
            # 여기서의 환경 변수도 여러분 상황에 맞게 작성하시면 됩니다!!!
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_TAG_NAME }}:latest
            sudo docker run -d -p 8080:8080 \
                -e CLIENT_ID=d21718e96e4084ceeeeb474c55d28d50
                -e DB_PASSWORD=1q2w3e4r
                -e DB_URL=jdbc:mysql://localhost:3306/pallow
                -e DB_USERNAME=root
                -e ACCESS_TOKEN_TTL=6400000
                -e REFRESH_TOKEN_TTL= 6400000
                -e JWT_SECRET_KEY=GziP2tKme5j8oPnIcJxJmv7j+sSev3J1tBRExWgnSMeBBYtGq+RFXjsbA+4E8G5lBPOAriDxEr8B2B7W9T+F0w==
                -e MAIL_PASSWORD=festtsobwrueciig
                -e MAIL_USERNAME=seo78200@gmail.com
                -e REDIRECT_URI=http://localhost:8080/auth/oauth/callback
                -e REDIS_HOST=localhost 
                -e REDIS_PORT=6379
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_TAG_NAME }}:latest
            
            
